### ISSUE TITLE
Possible collaboration?

### ISSUE THREAD

**Issue by btopro** [FlorianFe/chemical-element-visualisation#1]
Hey, awesome element! I just want to say how cool this was and see if there was any interest on possibly collaborating to take it further.

I work on elements for education called LRN https://github.com/LRNWebComponents and we've got a whole bunch of chemistry elements showing up in the near future for chemical reactions (one as an example: https://heymp.github.io/hydrolysis-element/components/hydrolysis-element/demo/index.html).

If there's any interest on collaborating to get this as something of a lrn-chemical-element type of tag w/ some enhanced accessibility let me know.

**Comment by FlorianFe** [comment]
Hello, I guess I have to reject. I don't have a lot of time at the moment, so i won't be able to help you with the LRN Elements. But I wish you much success with it :)
