### ISSUE TITLE
Change the size of the element

### ISSUE THREAD

**Issue by lastmjs** [FlorianFe/chemical-element-visualisation#3]
This thing is awesome! I'd really like to change the size of it though, controlling the width and height

**Comment by FlorianFe** [comment]
It should work now :) you can change the size with

`--chemical-element-visualisation-size: 50px`

for example to set the size 50x50 pixels. The standard value is 100%. The size is both width and height.

**Comment by lastmjs** [comment]
If the standard value is 100%, does that mean I can control its size by wrapping it in a container and setting the size on the container?

**Comment by FlorianFe** [comment]
yes, this should work :)
